# Generated by Django 6.0.4 on 2026-05-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
