# Generated by Django 6.0.4 on 2026-05-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_vendedor_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedor',
            name='cep_origem',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='chave_pix',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
